spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: demo
    password: demo
    hikari:
      minimum-idle: 30
      maximum-pool-size: 500
      connection-timeout: 30000
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: update
